---
title: "EDA Summary"
output: github_document
---

```{r, include=FALSE}

library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)


theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continous.colour = "viridis",
  ggplot2.continous.fill = "viridis"
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

##Load the weather data

```{r}

weather_df =  
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, everything())

weather_df

```

## 'group_by'

```{r}

#can use ungroup() to ungroup specific variables

weather_df %>%
  group_by(name, month)


```

## counting things

count month / name observations

```{r}

weather_df %>%
  group_by(name, month) %>%
  summarize(n_obs = n()) #n_obs is variable, n function sums

```

we can use 'count()'

```{r}

weather_df %>%
  count(month, name = "n_obs")

```

**NEVER** use base R's 'table'
    -result is not a DF
    -need to start in DF, then take it out of DF to use

```{r, eval=FALSE}

weather_df %>%
  pull(month) %>%
  table()

```

other helpful counters

```{r}

weather_df %>%
  group_by(month) %>%
  summarize(
    n_obs = n(),
    n_days = n_distinct(date))

```










